server:
  port: 8001

eureka:
  client:
    register-with-eureka: true  #注册到注册中心
    fetch-registry: true  #拉取服务列表
    service-url:
      defaultZone: http://win.eureka7001.com:7001/eureka, http://win.eureka7002.com:7002/eureka
#      defaultZone: http://localhost:7001/eureka

spring:
  application:
    name: cloud-payment-hystrix-service
