server:
  port: 7002
eureka:
  instance:
    hostname: win.eureka7002.com
#    hostname: localhost    #eureka 服务端的实例名称  单机版
  client:
    register-with-eureka: false  #是否向注册中心注册自己 默认 true
    fetch-registry: false  #是否需要检索服务 默认true
    service-url:
      defaultZone: http://win.eureka7001.com:7001/eureka
      #与注册中心交互的地址  查询和注册服务
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
